name: Daily Exchange-Rate Import

on:
  schedule:
    # 17:00 UTC = 18:00 CET
    - cron: '0 17 * * *'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      # 1) grab your code
      - uses: actions/checkout@v3

      # 2) install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) write the service account JSON into a file
      - name: Write service account key
        run: |
          echo "${{ secrets.FIREBASE_SA_JSON }}" > sa.json

      # 4) install your dependencies
      - name: Install dependencies
        run: |
          pip install firebase-admin requests

      # 5) run your script
      - name: Run updateRates.py
        run: |
          python updateRates.py sa.json
