name: Daily Exchange-Rate Import

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Write service account key
        run: |
          cat << 'EOF' > sa.json
          ${{ secrets.FIREBASE_SA_JSON }}
          EOF

      - name: Install dependencies
        run: |
          pip install firebase-admin requests

      - name: Run updateRates.py
        run: |
          python updateRates.py sa.json
